// Each sentence is a short English rendering of that lead's existing, sourced
// companyEvidence.statement. These are company facts, not claims of ELO,
// NL-W1201, or our coating material being purchased or used by the company.
// A new lead must receive its own reviewed sentence before email export.
export const leadEmailFacts: Record<string, string> = {
  'icl-charleston': 'I saw that your Charleston site produces coated controlled-release fertilizers.',
  'haifa-israel': 'I noticed Haifa Group markets the Multicote controlled-release fertilizer range.',
  'crf-agritech-st-thomas': 'Your St. Thomas site describes PurYield as polymer-coated urea.',
  'compo-expert-krefeld': 'Your controlled-release fertilizer range describes an elastic polymer coating around each granule.',
  'florikan-bowling-green': 'Profile Products describes Florikan coating fertilizer granules on its Florida production line.',
  'genus-brunswick': 'Your manufacturing information describes precision-coated fertilizers and in-house coating equipment.',
  'pol-coatings-twello': 'Your PO+ range includes a water-based primer for low-surface-energy plastics such as PP and PE.',
  'plastchem-hardenberg': 'Your Hardenberg facility develops custom flexible and rigid PVC compounds.',
  'aqua-based-us': 'Your primer range includes water-based extrusion-lamination primers for PP and PE films.',
  'deltachem-born': 'Your DeltaCote range includes coated urea, MAP and NPK fertilizers.',
  'cic-mckinney': 'Your Mustang range addresses adhesion on TPO and PP plastic surfaces.',
  'polyflex-baltic': 'Your Polyflex facility manufactures flexible and semi-rigid PVC formulations.',
  'stir-barletta': 'Your flexible PVC range includes highly plasticized custom compounds.',
  'pursell-sylacauga': 'Your company presents its products as a new generation of controlled-release fertilizers.',
  'cotex-dartmouth': 'Your technology information describes polymer-coated controlled-release fertilizers.',
  'simofert-beuningen': 'Your product range explicitly includes customized controlled-release fertilizers.',
  'sk-specialties-sibu': 'Your company describes using polymer-coating technology to make controlled-release fertilizers.',
  'smart-fert-klang': 'Your fertilizer range includes polymer-coated urea and other controlled-release products.',
  'simplot-boise': 'Your GAL-XeONE range is described as polymer-coated controlled-release fertilizer.',
  'agrofarm-ponorogo': 'Your ANR 30 CRF range describes a semipermeable polymer-resin coating.',
  'twin-arrow-shah-alam': 'Your manufacturing range includes Twin Supreme Controlled Release Fertilizer.',
  'agro-berjaya-mojokerto': 'An industry report describes your Ferti Best controlled-release fertilizer production in Mojokerto.',
  'diversatech-bangi': 'Your AJIB CRF range describes polymer-coated agglomeration technology.',
  'farmhannong-ulsan': 'Your fertilizer range includes coated urea, coated DAP and coated N-K products.',
  'jcam-agri-tokyo': 'Your LP-Coat and M-Coat ranges describe coated urea made with resin and mineral layers.',
  'jieh-ming-new-taipei': 'Your NonP PVC compound information lists plasticizer among its formulation materials.',
  'vinyl-base-ipoh': 'Your PVC compounding information discusses plasticizer selection for medical extrusion products.',
  'schramm-coatings-offenbach': 'The SCHRAMM water-based primer range lists products for PP/EPDM and ABS surfaces.',
  'periwal-bhiwadi': 'Your PVC compound specifications name plasticizers and stabilizers among the formulation inputs.',
  'turf-care-martins-ferry': 'Your Martins Ferry facility manufactures polymer-coated urea with several release-duration options.',
  'omega-polimeros-trujui': 'Your flexible PVC compound range describes the use of different plasticizers.',
  'supernovae-funza': 'Your PVC compounding description lists resin, plasticizer, stabilizer and lubricants as inputs.',
  'vivacor-diadema': 'Your water-based ink range includes products for PP twist wrap and HDPE shopping bags.',
  'agrobiotech-jardinopolis': 'Your Biocoat range describes polymer-coated urea for slow nutrient release.',
  'mica-shelton': 'Your catalog includes water-based primers and coatings for PP, PE, PVC and aluminum surfaces.',
  'ac-profil-huttwil': 'Your Huttwil operation combines in-house PVC compounding with profile extrusion.',
  'nutrien-carseland': 'Your ESN data sheet identifies a polymer-coated urea product made in Carseland.',
  'ichemco-cuggiono': 'Your water-based primer range includes products for PE, PP and PVC films.',
  'polymer-chemie-bad-sobernheim': 'Your PVC business describes customer-specific formulations and multiple compounding lines.',
  'astra-chemtech-mumbai': 'Your Astra Aqueous Primer is described for PP and BOPP film.',
  'nam-ah-ipoh': 'Your manufacturing range includes plasticized PVC compounds for several extrusion applications.',
  'dacarto-osasco': 'Your PVC compound information names plasticizers and stabilizers as formulation ingredients.',
  'flint-group-malmo': 'Your PremoFilm SXS/2 range includes water-based inks for polyolefin films.',
  'inx-schaumburg': 'Your Aquamax range describes water-based ink for HDPE shopping-bag applications.',
  'shakun-vadodara': 'Your SPL-VTEK-S 52 cable compound specification names plasticizers and stabilizers.',
  'pvc-colouring-ahmedabad': 'Your flexible PVC compound information publishes its plasticizer-content range.',
  'sun-chemical-parsippany': 'Your SunStrato AquaLam water-based ink range includes OPP/OPP and OPP/PE film structures.',
  'crf-malaysia-kuala-lumpur': 'Your Malaysian facilities describe polymer and film coating processes for controlled-release fertilizers.',
  'cai-georgetown': 'Your water-based flexographic and gravure ink range includes PE and PP films.',
  'applied-db-samut-prakan': 'Your annual report describes plasticizer as an input to your PVC compound production.',
  'ceccan-san-jose-iturbide': 'Your PVC compounding information describes dedicated plasticizer-storage capacity.',
  'central-chemical-ube': 'Your Cera-coat R range is described as a coated-urea controlled-release fertilizer.',
  'tintas-prisma-tlalnepantla': 'Your AQUAPOLY range includes water-based flexographic ink for HDPE film.',
  'alpha-plast-devland': 'Your PVC compounding process describes mixing plasticizers and stabilizers with PVC resin.',
  'mivena-maastricht': 'Your Maastricht facility makes Granucote and Horti-Cote coated fertilizers.',
  'greenbest-henstridge': 'Your Henstridge facility produces Nutrilong V90 polymer-coated urea.',
  'palini-vernici-pisogne': 'Your PALINAL range lists water-based primers for ABS and pretreated ABS/PP.',
  'sankhla-industries-bengaluru': 'Your SP90 PVC compound specification lists plasticizers and stabilizers.',
  'harrells-sylacauga': 'Your company describes a POLYON fertilizer-coating facility in Sylacauga.',
  'fortgreen-varginha': 'Origin Enterprises reported a resin-coated controlled-release fertilizer production line at Fortgreen in Varginha.',
  'grupo-equilibrio-catalao': 'Your eQcoat fertilizer range describes coating nutrient granules to regulate release.',
  'adubos-paranaiba-uberlandia': 'Your SUPERCOAT range includes polymer-coated urea, MAP and NPK fertilizers.',
  'indigrow-brimpton': 'Your Impact CGF range includes resin-coated urea fertilizers made in the UK.',
  'lebanon-seaboard-lebanon': 'Your professional fertilizer range includes polymer-coated urea controlled-release products.',
  'follmann-minden': 'Your water-based coatings range covers PP, PE and PET films.',
  'mapei-india-bengaluru': 'Your India business manufactures adhesives and sealants and lists a Bangalore facility.',
  'plantacote-herentals': 'Your Plantacote portfolio includes fully coated NPK and other controlled-release fertilizers.',
  'siegwerk-siegburg': 'Your white paper describes water-based inkjet inks for PE, PP, BOPP and PET substrates.',
  'jowat-detmold': 'Your industrial adhesive portfolio includes reactive SMP, PUR and epoxy systems.',
  'knox-fertilizer-knox': 'Your SurfCote range describes polymer-resin-encapsulated fertilizer granules.',
  'andersons-maumee': 'Your CarbonCoat product label lists polymer-coated humic-coated urea.',
  'doneck-euroflex-grevenmacher': 'Your Euro-Film range includes water-based inks for PE and PP films.',
  'wikoff-fort-mill': 'Your water-based ink range names HDPE, LDPE, polypropylene, BOPP and PET substrates.',
  'aurora-material-streetsboro': 'Your flexible PVC business describes optimizing plasticizer systems and stabilizer packages.',
  'sun-agro-tokyo': 'Your SCU and SC fertilizer ranges describe sulfur- and wax-coated granules.',
  'katakura-coop-akita': 'Your company history records fertilizer-coating equipment at the Akita plant.',
  'gefink-burzaco': 'Your GEF.WATER range includes water-based inks for PE film and PP flexography.',
  'colorprint-coseano': 'Your Idropol water-based flexographic ink range includes polyethylene printing.',
  'manner-polymers-mckinney': 'Your custom flexible PVC operation describes multiple compounding lines and formulation work.',
  'vernital-cercola': 'Your Vernitex range includes two-component epoxy anticorrosion coatings for industrial and marine settings.',
  'duramax-cascavel': 'Your Epóxi HS Poliamina range includes high-solids industrial anticorrosion coatings.',
  'marincoat-calvignasco': 'Your company describes formulating and producing coatings for pipelines and storage equipment.',
  'rynan-smart-fertilizers-long-duc': 'Your RYNAN Smart Fertilizers range describes a nano-polymer coating process.',
  'pungnong-seoul': 'Your production fact sheet lists controlled-release compound fertilizer at your second factory.',
  'ec-grow-eau-claire': 'Your company announced its own polymer-coating facility and now offers EPEC polymer-coated urea.',
  'sumika-agro-niihama': 'Your Ehime fertilizer plant lists coated-fertilizer production and dedicated coating-material tanks.',
  'nousbo-ulsan': 'Your Ulsan facility operates dedicated fluid-bed coating lines for controlled-release fertilizers.',
  'dupan-anugerah-lestari-pungging': 'Your PUPINDO production information describes a coating step used to make slow-release NPK fertilizer.',
  'hanampi-sejahtera-kahuripan-gresik': 'Your Haracoat range includes controlled-release urea with sulfur and polymer coating layers.',
  'dgo-defix-phu-nghia': 'Your DEFIX range includes epoxy anticorrosion coatings for marine vessels.',
  'son-mien-bac-hung-yen': 'Your Hung Yen factory describes manufacturing protective and anticorrosion coatings for steel structures.',
  'dolphin-inks-thane': 'Your flexible-packaging range includes water-based inks for polypropylene and polyethylene substrates.',
}
